// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: qrcode.proto

package qrcode

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Qrcode service

func NewQrcodeEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Qrcode service

type QrcodeService interface {
	GetQrcode(ctx context.Context, in *GetQrcodeRequest, opts ...client.CallOption) (*GetQrcodeResponse, error)
}

type qrcodeService struct {
	c    client.Client
	name string
}

func NewQrcodeService(name string, c client.Client) QrcodeService {
	return &qrcodeService{
		c:    c,
		name: name,
	}
}

func (c *qrcodeService) GetQrcode(ctx context.Context, in *GetQrcodeRequest, opts ...client.CallOption) (*GetQrcodeResponse, error) {
	req := c.c.NewRequest(c.name, "Qrcode.GetQrcode", in)
	out := new(GetQrcodeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Qrcode service

type QrcodeHandler interface {
	GetQrcode(context.Context, *GetQrcodeRequest, *GetQrcodeResponse) error
}

func RegisterQrcodeHandler(s server.Server, hdlr QrcodeHandler, opts ...server.HandlerOption) error {
	type qrcode interface {
		GetQrcode(ctx context.Context, in *GetQrcodeRequest, out *GetQrcodeResponse) error
	}
	type Qrcode struct {
		qrcode
	}
	h := &qrcodeHandler{hdlr}
	return s.Handle(s.NewHandler(&Qrcode{h}, opts...))
}

type qrcodeHandler struct {
	QrcodeHandler
}

func (h *qrcodeHandler) GetQrcode(ctx context.Context, in *GetQrcodeRequest, out *GetQrcodeResponse) error {
	return h.QrcodeHandler.GetQrcode(ctx, in, out)
}
